export const MENU = [
    {type: 'vegan', time: 'breakfast', name: 'Гречневая каша', ingredients: ['гречка']},
    {type: 'general', time: 'breakfast', name: 'Гречневая каша и яйца-пашот', ingredients: ['гречка', 'яйца']},
    {type: 'vegan', time: 'breakfast', name: 'Овсяная каша', ingredients: ['овсянка']},
    {type: 'general', time: 'breakfast', name: 'Пшенная каша с тыквой', ingredients: ['пшено', 'тыква']},
    {type: 'general', time: 'breakfast', name: 'Творожный сыр с хлебцами', ingredients: []},
    {type: 'general', time: 'lunch', name: 'Суп куриный с вермишелью', ingredients: ['курица', 'вермишель']},
    {type: 'general', time: 'lunch', name: 'Овощной суп-пюре с базиликом и рулетом из фарша с рисом', ingredients: ['курица', 'вермишель']},
    {type: 'general', time: 'lunch', name: 'Фасолевый борщ', ingredients: ['курица', 'вермишель']},
    {type: 'vegan', time: 'lunch', name: 'Морковный суп-пюре с хрустящим нутом, Салат с рукколой и редисом', ingredients: ['нут', 'редис', 'морковь', 'руккола', 'картофель']},
    {type: 'general', time: 'dinner', name: 'Рыбные тефтели с винегретом', ingredients: ['рыба', 'свекла']},
    {type: 'general', time: 'dinner', name: 'Голубцы', ingredients: ['фарш', 'капуста', 'рис']},
    {type: 'general', time: 'dinner', name: 'Плов', ingredients: ['рис', 'курица']},
    {type: 'general', time: 'dinner', name: 'Кинва с овощами гриль и котлеты из горбуши', ingredients: []},
    {type: 'general', time: 'dinner', name: 'Картошка с индейкой', ingredients: []},
    {type: 'general', time: 'dinner', name: 'Салат из кальмаров', ingredients: []},
    {type: 'vegan', time: 'dinner', name: 'Картофель тушеный с оливками и лимоном, Салат из свежей капусты с яблоком', ingredients: ['', '']},
    {type: 'general', time: 'dinner', name: 'Курица в горчичном соусе с гречкой', ingredients: ['курица', 'гречка']},
    {type: 'general', time: 'lunch', name: 'Рассольник', ingredients: []},
    {type: 'vegan', time: 'lunch', name: 'Борщ постный', ingredients: []},
    {type: 'general', time: 'snack', name: 'Салат из моркови и кураги', ingredients: ['морковь', 'курага']},
    {type: 'general', time: 'snack', name: 'Фруктовый коктейль с кефиром и творогом', ingredients: ['кефир', 'творог', 'фрукты']},
    {type: 'general', time: 'snack', name: 'Вареники с вишней или картошкой, кефир', ingredients: ['', '']},
    {type: 'general', time: 'snack', name: 'Творожное суфле, тост из цельнозернового хлеба с брынзой', ingredients: ['кефир', 'творог', 'фрукты']},
    {type: 'vegan', time: 'snack', name: 'Яблоко, запеченное с орехами', ingredients: []},
    {type: 'general', time: 'dinner', name: 'Печень в сметане c вермишелью и салат из моркови и кураги', ingredients: ['морковь', 'курага', 'печень', 'сметана']},
    {type: 'general', time: 'breakfast', name: '2 вареных яйца, бутерброд с фетой, помидорами', ingredients: ['батон', 'печень', 'хлеб']},
    {type: 'general', time: 'breakfast', name: 'Бутерброды с печеночным паштетом', ingredients: ['батон', 'печень', 'хлеб']},
    {type: 'general', time: 'lunch', name: 'Суп куриный с рисом', ingredients: ['рис', 'курица']},
    {type: 'vegan', time: 'lunch', name: 'Мисо-суп, паста с овощами и сыром тофу, груша/яблоко', ingredients: ['', '']},
    {type: 'vegan', time: 'lunch', name: 'Постные щи, лепешки из маша, смузи', ingredients: ['', '']},
    {type: 'vegan', time: 'lunch', name: 'Суп из нута, кус-кус с цветной капустой', ingredients: ['', '']},
    {type: 'vegan', time: 'lunch', name: 'Борщ без мяса, овощные котлеты, апельсин', ingredients: ['', '']},
    {type: 'general', time: 'snack', name: 'Рулет с лимоном', ingredients: ['батон', 'лимон']},
    {type: 'general', time: 'breakfast', name: 'Каша “Ассорти(рис,пшено)', ingredients: ['рис', 'пшено']},
    {type: 'general', time: 'dinner', name: 'Суп гороховый с чесночными гренками', ingredients: []},
    {type: 'general', time: 'dinner', name: 'Гороховый суп с томатной пастой, морковно-яблочный салат', ingredients: []},
    {type: 'general', time: 'breakfast', name: 'Омлет', ingredients: []},
    {type: 'vegan', time: 'breakfast', name: 'Ячневая каша с бананом', ingredients: []},
    {type: 'general', time: 'breakfast', name: 'Луковый пирог', ingredients: ['лук', 'яйца', 'сыр плавленный', 'мука']},
    {type: 'general', time: 'breakfast', name: 'Морковно-творожная запеканка', ingredients: []},
    {type: 'general', time: 'dinner', name: 'Дранники', ingredients: []},
    {type: 'vegan', time: 'dinner', name: 'Гречневая каша с яйцом; Гратен из кабачков и помидоров', ingredients: []},
    {type: 'vegan', time: 'dinner', name: 'Печеный картофель, икра из баклажанов, помидор', ingredients: []},
    {type: 'vegan', time: 'dinner', name: 'Бурый рис, овощи на гриле, кефир', ingredients: []},
    {type: 'vegan', time: 'dinner', name: 'Запеканка из цветной капусты, кабачков, картофеля', ingredients: []},
    {type: 'vegan', time: 'dinner', name: 'Овощная лазанья, ржаные хлебцы', ingredients: []},
    {type: 'vegan', time: 'dinner', name: 'Творожная запеканка, винегрет с авокадо, зеленый чай', ingredients: []},
    {type: 'vegan', time: 'dinner', name: 'Овощи, тушеные с грибами, бутерброд с кабачковой икрой', ingredients: []},
    {type: 'vegan', time: 'dinner', name: 'Отварная чечевица, салат из моркови, свеклы, чеснока со сметаной', ingredients: []},
    {type: 'vegan', time: 'dinner', name: 'Тофу с нутом, кабачками, баклажанами', ingredients: []},
    {type: 'vegan', time: 'dinner', name: 'Тофу с овощным салатом', ingredients: []},
    {type: 'vegan', time: 'breakfast', name: 'Лаваш с грибами, листьями салата и помидорами', ingredients: []},
    {type: 'vegan', time: 'breakfast', name: 'Коктейль из овсяного молока с ягодами и семенами льна', ingredients: ['лен', 'овсяное молоко', 'клубника', 'черника', 'банан', 'чиа']},
    {type: 'vegan', time: 'breakfast', name: 'Бутерброды с пастой из авокадо и фасолью', ingredients: ['лен', 'овсяное молоко', 'клубника', 'черника', 'банан', 'чиа']},
    {type: 'general', time: 'snack', name: 'Манники', ingredients: []},
    {type: 'vegan', time: 'snack', name: 'Шампиньоны с зеленым яблоком', ingredients: []},
    {type: 'vegan', time: 'snack', name: 'Хумус c морковью соломкой и сельдереем', ingredients: []},
    {type: 'general', time: 'snack', name: 'Сырники со сгущенкой', ingredients: []},
    {type: 'general', time: 'dinner', name: 'Картофель тушеный с оливками и лимоном, салат из капусты с огурцом', ingredients: []},
    {type: 'general', time: 'dinner', name: 'Пицца', ingredients: []},
    {type: 'general', time: 'snack', name: 'Оладьи с яблоками', ingredients: []},
    {type: 'vegan', time: 'snack', name: 'Рисовые хлебцы c арахисовой паста', ingredients: []},
    {type: 'vegan', time: 'snack', name: 'Тофу с орехами', ingredients: ['Тофу', 'банан', 'миндаль', 'клубника']},
    {type: 'vegan', time: 'snack', name: 'Фрукты (яблоки)', ingredients: []},
    {type: 'vegan', time: 'snack', name: ' Шарлотка с яблоками', ingredients: []},
    {type: 'general', time: 'dinner', name: 'Тушеная капуста с рисом и фаршем с салатом из морокови с чесноком', ingredients: []},
    {type: 'general', time: 'lunch', name: 'Суп с томатной пастой и лапшой', ingredients: []},
    {type: 'vegan', time: 'lunch', name: 'Грибной суп из вешенок, салат из огурцов и мяты', ingredients: []},
    {type: 'vegan', time: 'lunch', name: 'Грибной суп из шампиньонов, салат листовой', ingredients: []},
    {type: 'vegan', time: 'lunch', name: 'Чечевица с шампиньонами', ingredients: []},
    {type: 'vegan', time: 'lunch', name: 'Чечевица с овощами', ingredients: []},
    {type: 'vegan', time: 'lunch', name: 'Тушеная чечевица с овощными котлетами', ingredients: []},
    {type: 'vegan', time: 'lunch', name: 'Темный борщ с грибами и черносливом', ingredients: []},
    {type: 'vegan', time: 'lunch', name: 'Рассольник с перловкой, перец, фаршированный рисом и овощами', ingredients: []},
    {type: 'vegan', time: 'lunch', name: 'Мексиканский салат с овощами и авокадо', ingredients: []},
    {type: 'vegan', time: 'lunch', name: 'Крем-суп фасолевый, салат из свежих или отварных овощей', ingredients: []},
    {type: 'vegan', time: 'snack', name: 'Запеканка из брокколи и цветной капусты', ingredients: []},
    {type: 'vegan', time: 'snack', name: 'Йогурт соевый с огурцом, укропом, и зеленым луком', ingredients: []},
    {type: 'general', time: 'snack', name: 'Кефирный коктейль с бананом, имбирем и корицей', ingredients: []},
    {type: 'general', time: 'breakfast', name: 'Сырники с яблоками', ingredients: []},
    {type: 'vegan', time: 'dinner', name: 'Плов из перловой крупы с грибами, Салат из свежей свеклы с грецкими орехами', ingredients: []},
    {type: 'vegan', time: 'dinner', name: 'Стручковая фасоль с тофу и перцем', ingredients: []},
    {type: 'vegan', time: 'dinner', name: 'Рис с салатом из морской капусты', ingredients: []},
    {type: 'vegan', time: 'dinner', name: 'Маш с фасолью и листовым салатом', ingredients: []},
    {type: 'vegan', time: 'dinner', name: 'Соевое мясо с кашей из нескольких круп', ingredients: []},
    {type: 'vegan', time: 'dinner', name: 'Тушеные овощи с грибами', ingredients: []},
    {type: 'vegan', time: 'dinner', name: 'Запеканка с фасолью и картофельным пюре Салат из свежей капусты с яблоком', ingredients: []},
    {type: 'vegan', time: 'dinner', name: 'Гороховая каша на кокосовом масле с овощами', ingredients: []},
    {type: 'general', time: 'dinner', name: 'Куриные котлеткы с картофелем и салатом из свежей капусты с чесночной заправкой', ingredients: []},
    {type: 'general', time: 'dinner', name: 'Борщ с галушками и ростбиф', ingredients: []},
    {type: 'general', time: 'dinner', name: 'Рожки с брокколи и креветками с соусом песто', ingredients: []},
    {type: 'general', time: 'dinner', name: 'Говяжьи котлеты и рис и салатом из свеклы с зеленым горошком', ingredients: []},
    {type: 'general', time: 'dinner', name: 'Картофельное пюре с сардинами в масле', ingredients: []},
    {type: 'general', time: 'dinner', name: 'Картофельная запеканка с мясом', ingredients: []},
    {type: 'general', time: 'dinner', name: 'Блинчики с ливером', ingredients: []},
    {type: 'general', time: 'breakfast', name: 'Блинчики с творогом', ingredients: []},
    {type: 'general', time: 'breakfast', name: 'Пельмени', ingredients: []},
    {type: 'general', time: 'breakfast', name: 'Манная каша', ingredients: []},
    {type: 'vegan', time: 'snack', name: 'Бананы', ingredients: []},

]